# Logging Configuration
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
    
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  "":  # root logger
    level: DEBUG
    handlers: [console, file]
    propagate: false
    
  aiohttp:
    level: WARNING
    handlers: [file]
    propagate: false
    
  requests:
    level: WARNING
    handlers: [file]
    propagate: false
